//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimalDetail
    {
        public long animalId { get; set; }
        public long language { get; set; }
        public string name { get; set; }
        public string story { get; set; }
        public string category { get; set; }
        public string series { get; set; }
        public string family { get; set; }
        public string distribution { get; set; }
        public string reproduction { get; set; }
        public string food { get; set; }
    }
}
