//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int id { get; set; }
        public string deviceId { get; set; }
        public System.DateTime lastPing { get; set; }
        public double lastLongitude { get; set; }
        public double lastLatitude { get; set; }
    }
}
