//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enclosure
    {
        public long id { get; set; }
        public string name { get; set; }
        public string story { get; set; }
        public double markerLongitude { get; set; }
        public double markerLatitude { get; set; }
        public string markerIconUrl { get; set; }
        public string pictureUrl { get; set; }
        public long language { get; set; }
    }
}
