//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInfo
    {
        public string name { get; set; }
        public string aboutUs { get; set; }
        public string openingHoursNote { get; set; }
        public string contactInfoNote { get; set; }
        public string mapBackgroundUrl { get; set; }
        public long language { get; set; }
    }
}
