//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MiscMarker
    {
        public float longitude { get; set; }
        public float latitude { get; set; }
        public string iconUrl { get; set; }
        public long id { get; set; }
    }
}
