//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NegevZooDBEntities : DbContext
    {
        public NegevZooDBEntities()
            : base("name=NegevZooDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animals { get; set; }
        public virtual DbSet<ContactInfo> ContactInfos { get; set; }
        public virtual DbSet<EnclosurePicture> EnclosurePictures { get; set; }
        public virtual DbSet<Enclosure> Enclosures { get; set; }
        public virtual DbSet<GeneralInfo> GeneralInfos { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MiscMarker> MiscMarkers { get; set; }
        public virtual DbSet<OpeningHour> OpeningHours { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<RecommendedRoute> RecommendedRoutes { get; set; }
        public virtual DbSet<RecurringEvent> RecurringEvents { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<SpecialEvent> SpecialEvents { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<WallFeed> WallFeeds { get; set; }
        public virtual DbSet<YoutubeVideoUrl> YoutubeVideoUrls { get; set; }
        public virtual DbSet<AnimalDetail> AnimalDetails { get; set; }
        public virtual DbSet<EnclosureDetail> EnclosureDetails { get; set; }
        public virtual DbSet<Device> Devices { get; set; }
        public virtual DbSet<MapInfo> MapInfos { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<AnimalStory> AnimalStories { get; set; }
        public virtual DbSet<AnimalStoryDetail> AnimalStoryDetails { get; set; }
    }
}
