//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecurringEvent
    {
        public long id { get; set; }
        public string description { get; set; }
        public string day { get; set; }
        public long startHour { get; set; }
        public int startMin { get; set; }
        public long endHour { get; set; }
        public int endMin { get; set; }
        public int enclosureId { get; set; }
        public long language { get; set; }
    }
}
